Repository grooteogi/frontend, pull requests merged in 2022-05, with the labels that each got.

#60 feat: Add UI Search Page with responsive post card
  components/common/Dropdown/Dropdown.styled.ts
  components/common/PostCard/PostCard.styled.ts
  components/common/PostCard/PostCard.tsx
  components/common/SearchBar/SearchBar.styled.ts
  components/common/SearchButton/SearchButton.stories.tsx
  components/common/SearchButton/SearchButton.styled.ts
  components/common/SearchButton/SearchButton.tsx
  components/common/SearchMenu/SearchMenu.stories.tsx
  components/common/SearchMenu/SearchMenu.tsx
  components/layout/Content.tsx
  components/search/SearchPage.tsx
  components/search/stories/SearchPage.stories.tsx
  types/fetchedHashtag.ts
Labels: enhancement, feature

#61 Create meeting schedule component
  .yarn/cache/moment-npm-2.29.3-fe4ba99bae-2e780e36d9.zip
  components/common/Dropdown/Dropdown.stories.tsx
  components/common/Dropdown/Dropdown.tsx
  components/post/MeetingInfo/MeetingInfo.tsx
  components/post/ShowSchedule/MeetingSchedule.style.ts
  components/post/ShowSchedule/MeetingSchedule.tsx
  components/post/ShowSchedule/index.stories.tsx
  components/post/ShowSchedule/index.tsx
  package.json
  yarn.lock
Labels: enhancement, feature

#63 feat: Create Image component
  components/common/Image/Image.stories.tsx
  components/common/Image/Image.styled.ts
  components/common/Image/Image.tsx
  components/common/Image/index.tsx
Labels: enhancement, feature

#65 fix: Add default width 100%, remove unnecessary margin values
  components/common/Box/Box.styled.ts
Labels: fix

#66 refactor: Refactor move dateformattor func to lib/common.ts
  components/post/ShowSchedule/MeetingSchedule.tsx
  lib/common.ts
Labels: refactoring

#67 refactor: Refactor types of common.ts & entity.ts
  types/common.ts
  types/entity.ts
Labels: enhancement, refactoring

#72 Hotfix Input Component & Textarea Component style
  components/common/Input/Input.stories.tsx
  components/common/Input/Input.styled.ts
  components/common/Input/Input.tsx
  components/common/Textarea/Textarea.styled.ts
  components/common/Textarea/Textarea.tsx
  components/common/Textarea/textarea.stories.tsx
Labels: fix

#71 refactor: Add common html attributes to pure html based components
  components/common/Box/Box.tsx
  components/common/Button/Button.tsx
  components/common/Checkbox/Checkbox.tsx
Labels: refactoring

#64 refactor: button menu is for single click, buttons do not have clicke…
  components/common/SearchBar/SearchBar.stories.tsx
  components/common/SearchBar/SearchBar.tsx
  components/common/SearchButton/SearchButton.stories.tsx
  components/common/SearchButton/SearchButton.tsx
  components/common/SearchMenu/SearchMenu.tsx
  components/post/MeetingInfoEdit/MeetingInfoEdit.tsx
  components/search/SearchPage.tsx
Labels: fix

#74 Hotfix component hashtag
  components/auth/SelectHashtagModal.tsx
  components/common/Hashtag/Hashtag.stories.tsx
  components/common/Hashtag/Hashtag.tsx
  components/common/PostCard/PostCard.stories.tsx
  components/common/PostCard/PostCard.tsx
  components/common/SearchButton/SearchButton.stories.tsx
  components/common/SearchButton/SearchButton.tsx
  components/common/SearchMenu/SearchMenu.stories.tsx
  components/common/SearchMenu/SearchMenu.tsx
  components/common/SearchMenu/data.json
  components/post/MeetingInfo/MeetingInfo.tsx
  components/post/MeetingInfo/index.stories.tsx
  components/post/MeetingInfoEdit/MeetingInfoEdit.tsx
  components/post/detail.mock.ts
  components/search/SearchPage.tsx
  types/entity.ts
  types/fetchedHashtag.ts
Labels: fix

#78 Create build test
  .github/workflows/build_test.yml
Labels: enhancement

#79 Reservation page
  .yarn/cache/deepmerge-npm-2.2.1-44c00cbffa-284b710650.zip
  .yarn/cache/formik-npm-2.2.9-0e8cb516ca-f07f80eee8.zip
  .yarn/cache/lodash-es-npm-4.17.21-b45832dfce-05cbffad6e.zip
  .yarn/cache/react-fast-compare-npm-2.0.4-ab3f6356e2-06046595f9.zip
  .yarn/cache/tiny-warning-npm-1.0.3-750b7a07c4-da62c4acac.zip
  components/auth/AuthModal.tsx
  components/auth/SelectHashtagModal.tsx
  components/auth/SignInModal.tsx
  components/auth/SignUpModal.tsx
  components/auth/layout.ts
  components/auth/stories/SelectHashtagModal.stories.tsx
  components/auth/stories/SignInModal.stories.tsx
  components/auth/stories/SignUpModal.stories.tsx
  components/auth/style.ts
  components/common/Checkbox/Checkbox.styled.ts
  components/common/Checkbox/Checkbox.tsx
  components/common/Input/Input.stories.tsx
  components/common/Input/Input.styled.ts
  components/common/Input/Input.tsx
  components/common/ScheduleItem/ScheduleItem.stories.tsx
  components/common/ScheduleItem/ScheduleItem.styled.tsx
  components/common/ScheduleItem/ScheduleItem.tsx
  components/common/ScheduleItem/index.tsx
  components/common/Textarea/Textarea.styled.ts
  components/common/Textarea/Textarea.tsx
  components/common/Timer/Timer.tsx
  components/reservation/MentorProfile/MentorProfile.styled.tsx
  components/reservation/MentorProfile/MentorProfile.tsx
  components/reservation/ReservationForm/ReservationForm.styled.tsx
  components/reservation/ReservationForm/ReservationForm.tsx
  components/reservation/SelectReservationPanel/SelectReservationPanel.styled.tsx
  components/reservation/SelectReservationPanel/SelectReservationPanel.tsx
  components/reservation/context.tsx
  components/reservation/layout.ts
  hooks/useSigninMutation.tsx
  lib/api/auth.ts
  lib/api/reservation.ts
  package.json
  pages/_app.tsx
  pages/auth/hashtag.tsx
  pages/auth/index.tsx
  pages/auth/signin.tsx
  pages/auth/signup.tsx
  pages/reservation/index.tsx
  public/imgs/profile.png
  styles/GlobalStyle.tsx
  styles/theme.ts
  types/entity.ts
  types/general.tsx
  yarn.lock
Labels: enhancement, feature, refactoring

#84 Refactor UI reservation page
  components/common/Header/Header.styled.ts
  components/reservation/MentorProfile/MentorProfile.tsx
  components/reservation/ReservationForm/ReservationForm.tsx
  components/reservation/context.tsx
  lib/api/reservation.ts
  lib/api/restApi.ts
  pages/_app.tsx
  types/api.tsx
  types/entity.ts
Labels: refactoring

#87 Next.js Build Caching with GitHub Actions
  .github/workflows/build_test.yml
  .github/workflows/pr_test.yml
Labels: setting

#88 Yarn Berry Caching with GitHub Actions
  .github/workflows/build_test.yml
  .github/workflows/chromatic.yml
  .github/workflows/pr_test.yml
Labels: setting

#90 Create mypage SideBar Component
  components/mypage/SideBar/SideBar.stories.tsx
  components/mypage/SideBar/SideBar.styled.ts
  components/mypage/SideBar/SideBar.tsx
  components/mypage/SideBar/index.tsx
Labels: enhancement, feature

#89 Change SearchPage Layout
  components/common/SortingTab/SortingTab.styled.ts
  components/search/SearchFiltering/SearchFiltering.styled.tsx
  components/search/SearchFiltering/SearchFiltering.tsx
  components/search/SearchFiltering/index.tsx
  components/search/SearchInput/SearchInput.styled.tsx
  components/search/SearchInput/SearchInput.tsx
  components/search/SearchInput/index.tsx
  components/search/SearchInputs/SearchInputs.styled.tsx
  components/search/SearchInputs/SearchInputs.tsx
  components/search/SearchList/SearchList.styled.tsx
  components/search/SearchList/SearchList.tsx
  components/search/SearchList/index.tsx
  components/search/SearchMenu/HorizontalScroll/HorizontalScroll.style.ts
  components/search/SearchMenu/HorizontalScroll/HorizontalScroll.tsx
  components/search/SearchMenu/HorizontalScroll/index.ts
  components/search/SearchMenu/SearchMenu.stories.tsx
  components/search/SearchMenu/SearchMenu.styled.tsx
  components/search/SearchMenu/SearchMenu.tsx
  components/search/SearchMenu/data.json
  components/search/context.tsx
  components/search/layout.ts
  lib/api/post.ts
  lib/api/search.ts
  pages/index.tsx
  pages/search/index.tsx
  types/enum.tsx
Labels: refactoring

#92 Grtg 335 refactoring header component
  .yarn/cache/framer-motion-npm-6.3.4-421a042976-ea4ea22059.zip
  .yarn/cache/framesync-npm-6.0.1-937c080b05-a23ebe8f7e.zip
  .yarn/cache/hey-listen-npm-1.0.8-adb7dae9da-6bad60b367.zip
  .yarn/cache/popmotion-npm-11.0.3-120f81eddd-9fe7d03b4e.zip
  .yarn/cache/style-value-types-npm-5.0.0-ba441f7a16-16d198302c.zip
  components/auth/SignInModal.tsx
  components/auth/context.tsx
  components/auth/layout.ts
  components/auth/style.ts
  components/common/Link/Link.tsx
  components/layout/Content.tsx
  components/layout/Header/Header.styled.ts
  components/layout/Header/Header.tsx
  components/layout/Header/Logo.tsx
  package.json
  pages/_app.tsx
  styles/GlobalStyle.tsx
  types/entity.ts
  yarn.lock
Labels: enhancement, feature

#93 Header ref type 수정
  components/layout/Header/Header.tsx
Labels: refactoring

#91 Create Footer Component
  components/common/Footer/Footer.stories.tsx
  components/common/Footer/Footer.styled.ts
  components/common/Footer/Footer.tsx
  components/common/Footer/index.ts
  styles/theme.ts
Labels: enhancement, feature

#95 Update to skip steps when cache is present
  .github/workflows/build_test.yml
  .github/workflows/chromatic.yml
  .github/workflows/pr_test.yml
Labels: setting

#96 Eslint Caching with GitHub Actions
  .github/workflows/pr_test.yml
  .gitignore
  package.json
Labels: setting

#94 feat: Create MyPageCard component
  components/common/Image/Image.stories.tsx
  components/common/Image/Image.styled.ts
  components/common/MyPageCard/MyPageCard.stories.tsx
  components/common/MyPageCard/MyPageCard.styled.ts
  components/common/MyPageCard/MyPageCard.tsx
  components/common/MyPageCard/index.tsx
  components/common/PostCard/PostCard.stories.tsx
  components/common/PostCard/PostCard.styled.ts
  components/common/PostCard/PostCard.tsx
  components/common/SortingTab/SortingTab.tsx
  components/common/Typography/Typography.styled.ts
  components/search/SearchList/SearchList.tsx
  components/search/context.tsx
  lib/api/post.ts
  public/imgs/SamplePost.jpeg
  public/imgs/dev_sample.jpg
Labels: enhancement

#100 Refactor register auth
  components/auth/AuthModal.tsx
  components/auth/SignInModal.tsx
  components/auth/SignUpModal.tsx
  components/auth/layout.ts
  components/auth/style.ts
  components/common/Checkbox/Checkbox.tsx
Labels: refactoring

#101 refactor: Refactor auth lib
  lib/api/auth.ts
Labels: refactoring

#97 마이페이지 레이아웃 제작
  components/mypage/layout.tsx
  pages/mypage/likes.tsx
Labels: enhancement, feature

#105 Cache가 존재할 때 빌드되지 않는 오류 해결
  .github/workflows/build_test.yml
  package.json
Labels: setting

#107 refactor: Resolve minor errors
  components/auth/SignUpModal.tsx
  components/common/Box/Box.stories.tsx
  components/common/Dropdown/Dropdown.tsx
  components/common/Footer/Footer.styled.ts
  components/common/Image/Image.styled.ts
  components/common/ScheduleItem/ScheduleItem.tsx
  components/common/Wrapper/Wrapper.styled.ts
  components/post/MeetingInfo/MeetingInfo.style.tsx
  components/post/MeetingInfoEdit/MeetingInfoEdit.style.tsx
  components/post/MeetingInfoEdit/MeetingInfoEdit.tsx
  components/post/StickyBar/StickyBar.style.tsx
  components/post/StickyBar/StickyBar.tsx
  components/reservation/SelectReservationPanel/SelectReservationPanel.tsx
  lib/api/auth.ts
  lib/api/client.ts
  lib/api/post.ts
  lib/api/reservation.ts
  lib/api/search.ts
  lib/common.ts
  pages/_document.tsx
Labels: bug, fix, refactoring

#104 Hotfix Post Stickybar Component
  components/post/StickyBar/StickyBar.style.tsx
  components/post/layout.ts
Labels: bug, fix

#108 Feature post api 연결
  components/common/Button/Button.tsx
  components/common/Title/Title.styled.ts
  components/layout/Header/Header.tsx
  components/post/MeetingInfoEdit/AddHashtagBar/AddHashtagBar.tsx
  components/post/MeetingInfoEdit/MeetingInfoEdit.tsx
  components/post/MeetingInfoEdit/UploadImage/UploadImage.styled.ts
  components/post/MeetingInfoEdit/UploadImage/UploadImage.tsx
  components/post/MeetingInfoEdit/UploadImage/camera.svg
  components/post/ScheduleEdit/ScheduleEdit.style.ts
  components/post/ScheduleEdit/ScheduleEdit.tsx
  components/post/ScheduleShow/ScheduleShow.tsx
  components/post/StickyBar/StickyBar.style.tsx
  components/post/context.tsx
  lib/api/image.ts
  lib/api/post.ts
  lib/common.ts
  pages/post/[postId].tsx
  styles/GlobalStyle.tsx
  styles/theme.ts
Labels: enhancement, feature

#110 feat: 회원가입 시 유효성 검사 진행
  components/auth/SignUpModal.tsx
  components/common/Timer/Timer.tsx
  lib/validator.ts
Labels: feature

#109 feat: 메인페이지 -> 결과페이지 라우팅
  components/search/PageCarousel/PageCarousel.tsx
  components/search/PageCarousel/index.tsx
  components/search/ResultPage.tsx
  components/search/SearchBar/SearchBar.tsx
  components/search/SearchFiltering/SearchFiltering.styled.tsx
  components/search/SearchInput/SearchInput.styled.tsx
  components/search/SearchInput/SearchInput.tsx
  components/search/SearchList/SearchList.tsx
  components/search/SearchMenu/SearchMenu.styled.tsx
  components/search/SearchMenu/SearchMenu.tsx
  components/search/SearchPage.tsx
  components/search/context.tsx
  components/search/layout.ts
  lib/api/search.ts
  pages/index.tsx
  pages/search/index.tsx
  pages/search/result.tsx
  pages/search/search.tsx
Labels: enhancement

#112 Refactor Auth refresh logic
  components/auth/SignUpModal.tsx
  components/auth/style.ts
  components/post/MeetingInfoEdit/MeetingInfoEdit.tsx
  components/reservation/ReservationForm/ReservationForm.tsx
  components/search/SearchList/SearchList.tsx
  lib/api/auth.ts
  lib/api/client.ts
  lib/storage.ts
  pages/_document.tsx
Labels: enhancement, feature, refactoring
