Repository grooteogi/frontend, pull requests merged in 2022-06, with the labels that each got.

#113 프로필 수정 페이지
  .eslintcache
  components/auth/SignUpModal.tsx
  components/common/PostCard/PostCard.tsx
  components/common/PostCard/PostSkeleton.tsx
  components/mypage/SideBar/SideBar.tsx
  components/mypage/layout.tsx
  pages/mypage/likes.tsx
  pages/mypage/posts.tsx
  pages/mypage/profile.tsx
Labels: enhancement, feature

#114 Call scroll api based on data.pageCount
  components/search/SearchList/SearchList.tsx
  lib/api/client.ts
Labels: fix

#115 Add blur on auto complete
  components/search/SearchBar/SearchBar.tsx
Labels: enhancement, feature

#119 [Post api] Post create, detail api connection
  components/post/MeetingInfo/MeetingInfo.style.tsx
  components/post/MeetingInfo/MeetingInfo.tsx
  components/post/ScheduleShow/ScheduleShow.tsx
  components/post/usePost.tsx
  components/post/useReviews.tsx
  components/post/useSchedules.tsx
  lib/api/client.ts
  lib/api/post.ts
  pages/post/[postId].tsx
Labels: enhancement, feature

#124 Update postCard detail routing and fix typescript warnings
  components/common/PostCard/PostCard.stories.tsx
  components/common/PostCard/PostCard.tsx
  components/search/SearchList/SearchList.tsx
  types/entity.ts
  types/response.ts
Labels: enhancement, feature

#123 post review api 연결
  components/asset/flag_circle_black_24dp.svg
  components/common/PostCard/PostCard.stories.tsx
  components/post/MeetingInfo/MeetingInfo.style.tsx
  components/post/MeetingInfo/MeetingInfo.tsx
  components/post/MeetingInfoEdit/AddHashtagBar/AddHashtagBar.tsx
  components/post/MeetingInfoEdit/MeetingInfoEdit.tsx
  components/post/ReviewList/ReviewList.tsx
  components/post/ScheduleEdit/ScheduleEdit.tsx
  components/post/ScheduleShow/ScheduleShow.tsx
  components/post/context.tsx
  components/post/detail.meetingInfo.mock.ts
  components/post/detail.review.mock.ts
  components/post/detail.schedule.mock.ts
  components/post/useLikeMutate.tsx
  components/post/usePost.tsx
  components/post/useReviews.tsx
  hooks/useRouteWarning.tsx
  lib/api/client.ts
  lib/api/post.ts
  lib/storage.ts
  pages/post/[postId].tsx
  pages/post/create.tsx
  pages/post/edit/[postId].tsx
  styles/GlobalStyle.tsx
  types/entity.ts
  types/enum.tsx
  types/request.ts
  types/response.ts
Labels: enhancement, feature

#127 Hotfix signin page
  .yarn/cache/jwt-decode-npm-3.1.2-bf3ab26591-20a4b072d4.zip
  components/auth/SignUpModal.tsx
  components/common/Input/Input.styled.ts
  components/layout/Header/Header.styled.ts
  components/layout/Header/Header.tsx
  lib/api/auth.ts
  lib/api/client.ts
  lib/storage.ts
  package.json
  yarn.lock
Labels: enhancement, feature, refactoring

#130 fix: Resolve invalid path error
  .github/workflows/pr_test.yml
  package.json
Labels: setting

#131 JWT token Issue 해결
  components/mypage/layout.tsx
  components/mypage/useReservationList.tsx
  lib/api/client.ts
  lib/api/reservation.ts
  lib/storage.ts
  pages/post/edit/[postId].tsx
  types/enum.tsx
Labels: feature, fix

#132 Change mypage style
  components/mypage/MyPageCard/MyPageCard.tsx
  components/mypage/SideBar/SideBar.styled.ts
Labels: bug, fix

#134 Change reservation page responsive
  components/common/ScheduleItem/ScheduleItem.tsx
  components/mypage/MyPageCard/MyPageCard.styled.ts
  components/mypage/MyPageCard/MyPageCard.tsx
  components/mypage/MyPagePostCard/MyPagePostCard.tsx
  components/post/MeetingInfo/MeetingInfo.tsx
  components/reservation/MentorProfile/MentorProfile.styled.tsx
  components/reservation/MentorProfile/MentorProfile.tsx
  components/reservation/ReservationForm/ReservationForm.styled.tsx
  components/reservation/ReservationForm/ReservationForm.tsx
  components/reservation/SelectReservationPanel/SelectReservationPanel.styled.tsx
  components/reservation/SelectReservationPanel/SelectReservationPanel.tsx
  components/reservation/layout.ts
  components/reservation/reservation.post.mock.json
  components/reservation/reservation.schedules.mock.json
  pages/reservation/[postId].tsx
Labels: enhancement, feature

#136 feat: Add modify password
  components/mypage/Modify/Modify.tsx
  components/mypage/PasswordModal/PasswordForm.tsx
  components/mypage/PasswordModal/PasswordModal.styled.tsx
  components/mypage/PasswordModal/PasswordModal.tsx
  components/mypage/PasswordModal/index.tsx
  lib/api/user.ts
  types/request.ts
Labels: bug, fix

#138 fix: Fix Sorting tab
  components/common/SortingTab/SortingTab.styled.ts
  components/search/SearchFiltering/SearchFiltering.styled.tsx
Labels: enhancement

#140 fix: Change main page ui issues
  components/search/SearchBar/SearchBar.styled.ts
  components/search/SearchBar/SearchBar.tsx
  lib/api/post.ts
Labels: bug, fix

#141 Hotfix mypage
  components/mypage/Modify/Modify.tsx
  components/mypage/PasswordModal/PasswordForm.tsx
  components/mypage/PasswordModal/PasswordModal.tsx
  components/mypage/useProfile.tsx
  lib/api/user.ts
  pages/mypage/profile.tsx
  public/imgs/default_profile.png
Labels: bug, fix

#142 Style 수정하기
  components/auth/AuthModal.tsx
  components/auth/SignInModal.tsx
  components/auth/SignUpModal.tsx
  components/auth/layout.ts
  components/auth/style.ts
  components/common/Carousel/Carousel.stories.tsx
  components/common/Carousel/Carousel.tsx
  components/layout/Footer/Footer.styled.ts
  components/mypage/Content.tsx
  components/mypage/layout.tsx
  components/post/MeetingInfoEdit/AddHashtagBar/AddHashtagBar.tsx
  components/search/PageCarousel/PageCarousel.tsx
  pages/mypage/apply.tsx
  pages/mypage/likes.tsx
  pages/mypage/posts.tsx
  pages/mypage/profile.tsx
  pages/mypage/receive.tsx
  pages/post/[postId].tsx
  public/imgs/Carousel2.png
  public/imgs/Carousel3.png
  public/imgs/Carousel4.png
  public/imgs/Carousel5.png
  public/imgs/CarouselBasic.png
Labels: bug, fix

#148 fix: Add auto complete list click to route result page
  components/common/Image/Image.styled.ts
  components/common/PostCard/PostCard.stories.tsx
  components/common/PostCard/PostCard.tsx
  components/common/PostCard/PostSkeleton.tsx
  components/search/PageCarousel/PageCarousel.tsx
  components/search/SearchBar/SearchBar.tsx
  components/search/SearchInput/SearchInput.tsx
  components/search/SearchList/SearchList.styled.tsx
  components/search/SearchList/SearchList.tsx
  components/search/SearchMenu/SearchMenu.tsx
  components/search/context.tsx
  components/search/layout.ts
  components/search/usePosts.ts
  lib/api/post.ts
  pages/_app.tsx
  pages/search/result.tsx
  public/imgs/default_post.png
Labels: bug, fix

#158 fix: inifinite scroll div has no child
  components/search/SearchList/SearchList.tsx
Labels: bug, fix

#160 fix: Move Alert tag to the outer side of the tags
  components/mypage/MyPageCard/MyPageCard.tsx
  components/search/SearchBar/SearchBar.tsx
Labels: bug, fix

#163 fix: Add width at postPic image
  components/post/MeetingInfo/MeetingInfo.style.tsx
Labels: bug, fix
