Repository grooteogi/frontend, pull requests merged in 2022-04, with the labels that each got.

#20 Setting storybook chromatic preview
  .github/workflows/chromatic.yml
  .github/workflows/pr_test.yml
  .gitignore
  .yarn/cache/chromatic-npm-6.5.3-df64ee3cba-42b824ec1e.zip
  package.json
  yarn.lock
Labels: setting

#21 Change to work only when pushed to the develop branch
  .github/workflows/chromatic.yml
Labels: setting

#22 Add ui-test branch to trigger
  .github/workflows/chromatic.yml
Labels: setting

#11 Create Input Component
  src/components/Button/style.ts
  src/components/Input/index.stories.tsx
  src/components/Input/index.tsx
  src/components/Input/style.ts
  styles/theme.ts
Labels: enhancement, feature

#15 Create box, hashtag, link component
  src/components/Box/index.stories.tsx
  src/components/Box/index.tsx
  src/components/Box/style.ts
  src/components/Button/style.ts
  src/components/Hashtag/index.stories.tsx
  src/components/Hashtag/index.tsx
  src/components/Hashtag/style.ts
  src/components/Link/index.stories.tsx
  src/components/Link/index.tsx
  src/components/Link/style.ts
  styles/theme.ts
Labels: enhancement, feature

#17 Create UI button component
  .storybook/preview.js
  public/logos/google_logo.png
  public/logos/kakao_logo.png
  public/vercel.svg
  src/components/Button/index.stories.tsx
  src/components/Button/index.tsx
  src/components/Button/style.ts
  styles/theme.ts
Labels: enhancement, feature

#23 Create UI typography component
  .storybook/main.js
  src/components/Typography/index.stories.tsx
  src/components/Typography/index.tsx
  src/components/Typography/style.ts
  stories/Introduction.stories.mdx
  stories/assets/code-brackets.svg
  stories/assets/colors.svg
  stories/assets/comments.svg
  stories/assets/direction.svg
  stories/assets/flow.svg
  stories/assets/plugin.svg
  stories/assets/repo.svg
  stories/assets/stackalt.svg
  stories/button.css
  stories/header.css
  stories/page.css
  styles/GlobalStyle.tsx
  styles/theme.ts
Labels: enhancement, feature

#25 Change Input Component
  src/components/Input/index.stories.tsx
  src/components/Input/index.tsx
  src/components/Input/style.ts
  styles/theme.ts
Labels: enhancement, feature

#24 Change Box Component
  src/components/Box/index.tsx
  src/components/Box/style.ts
Labels: enhancement, feature

#26 Change Checkbox Component
  src/components/Checkbox/index.stories.tsx
  src/components/Checkbox/index.tsx
  src/components/Checkbox/style.ts
Labels: bug

#27 Create UI title component
  public/logos/google_logo.png
  public/logos/grooteogi_logo.png
  public/logos/kakao_logo.png
  src/components/Button/index.tsx
  src/components/Button/style.ts
  src/components/Title/index.stories.tsx
  src/components/Title/index.tsx
  src/components/Title/style.ts
  src/components/Typography/style.ts
  styles/theme.ts
  types/style.tsx
Labels: enhancement, feature

#33 Create UI Normal Sign up Modal
  pages/index.tsx
  src/components/Checkbox/index.tsx
  src/components/Checkbox/style.ts
  src/containers/NormalSignupModal/index.stories.tsx
  src/containers/NormalSignupModal/index.tsx
Labels: enhancement, feature

#34 Hotfix button fontweight
  src/components/Button/style.ts
Labels: fix

#32 Create Normal signin Modal
  src/containers/NormalSignInModal/index.stories.tsx
  src/containers/NormalSignInModal/index.tsx
Labels: enhancement, feature

#38 refactor: Add password Input style
  src/components/Input/index.tsx
  src/containers/NormalSignInModal/index.stories.tsx
  src/containers/NormalSignInModal/index.tsx
  src/containers/NormalSignupModal/index.tsx
Labels: enhancement, feature

#37 Create Sorting Tab Component
  src/components/SortingTab/index.stories.tsx
  src/components/SortingTab/index.tsx
  src/components/SortingTab/style.ts
  styles/theme.ts
Labels: enhancement, feature

#40 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: enhancement, feature

#39 Create layout
  src/layouts/index.tsx
Labels: enhancement, feature

#41 Create UI locale dropdown component
  public/icons/expand_more.png
  src/components/Dropdown/index.stories.tsx
  src/components/Dropdown/index.tsx
  src/components/Dropdown/style.ts
Labels: enhancement, feature

#42 Change Header Props and style
  src/components/Header/index.stories.tsx
  src/components/Header/index.tsx
  src/components/Header/style.ts
  styles/theme.ts
Labels: enhancement, feature

#45 UI post card component
  public/logos/dev_sample.jpg
  src/components/PostCard/index.stories.tsx
  src/components/PostCard/index.tsx
  src/components/PostCard/style.ts
  src/components/Title/style.ts
  src/containers/SelectHashtagModal/index.tsx
  styles/theme.ts
Labels: enhancement, feature

#47 UI search bar component
  public/logos/arrow-up.png
  public/logos/search.png
  src/components/SearchBar/data.json
  src/components/SearchBar/index.stories.tsx
  src/components/SearchBar/index.tsx
  src/components/SearchBar/style.ts
  src/hooks/useInput.tsx
  styles/theme.ts
Labels: enhancement, feature

#46 Create UI carousel component
  .yarn/cache/@types-react-slick-npm-0.23.8-1fd5949a0d-df71ab6b0f.zip
  .yarn/cache/classnames-npm-2.3.1-f2ae0a8d3c-14db8889d5.zip
  .yarn/cache/enquire.js-npm-2.1.6-fc4ea2e583-bb094054ee.zip
  .yarn/cache/json2mq-npm-0.2.0-aa8a6516b9-5672c3abdd.zip
  .yarn/cache/react-slick-npm-0.28.1-c38d7b328a-399ad43b9e.zip
  .yarn/cache/resize-observer-polyfill-npm-1.5.1-603120e8a0-57e7f79489.zip
  .yarn/cache/slick-carousel-npm-1.8.1-8382d373c2-acaad391e4.zip
  .yarn/cache/string-convert-npm-0.2.1-f1a42cb9ea-1098b1d8e3.zip
  package.json
  public/imgs/Carousel1.png
  public/imgs/Carousel2.png
  public/imgs/Carousel3.png
  public/imgs/Carousel4.png
  public/imgs/Carousel5.png
  public/imgs/CarouselBasic.png
  src/components/Carousel/Carousel.style.tsx
  src/components/Carousel/Carousel.tsx
  src/components/Carousel/index.stories.tsx
  src/components/Carousel/index.ts
  src/components/SortingTab/SortingTab.style.ts
  src/components/SortingTab/SortingTab.tsx
  src/components/SortingTab/index.stories.tsx
  src/components/SortingTab/index.ts
  src/components/SortingTab/index.tsx
  src/components/SortingTab/style.ts
  yarn.lock
Labels: enhancement, feature

#50 UI hashtag menu component
  public/logos/left.png
  public/logos/right.png
  src/components/Box/index.stories.tsx
  src/components/Box/style.ts
  src/components/SearchButton/SearchButton.style.ts
  src/components/SearchButton/SearchButton.tsx
  src/components/SearchButton/index.stories.tsx
  src/components/SearchButton/index.ts
  src/containers/SearchMenu/SearchMenu.style.ts
  src/containers/SearchMenu/SearchMenu.tsx
  src/containers/SearchMenu/data.json
  src/containers/SearchMenu/index.stories.tsx
  src/containers/SearchMenu/index.ts
Labels: enhancement, feature

#53 refactor: hashtag, postcard, search bar
  src/components/Hashtag/Hashtag.style.ts
  src/components/Hashtag/Hashtag.tsx
  src/components/Hashtag/index.stories.tsx
  src/components/Hashtag/index.ts
  src/components/PostCard/PostCard.style.ts
  src/components/PostCard/PostCard.tsx
  src/components/PostCard/index.stories.tsx
  src/components/PostCard/index.ts
  src/components/PostCard/style.ts
  src/components/SearchBar/SearchBar.style.ts
  src/components/SearchBar/SearchBar.tsx
  src/components/SearchBar/index.stories.tsx
  src/components/SearchBar/index.ts
  src/components/SearchBar/style.ts
  src/containers/SelectHashtagModal/data.ts
  src/containers/SelectHashtagModal/index.tsx
  types/fetchedHashtag.ts
Labels: enhancement, feature

#52 Add responsive to Box component, change box dimension props to optional
  src/components/Box/Box.tsx
  src/components/Box/index.stories.tsx
  src/components/Box/index.ts
  src/components/Box/index.tsx
  src/components/Box/style.ts
Labels: fix

#54 Refactor input component
  src/components/Input/Input.tsx
  src/components/Input/index.stories.tsx
  src/components/Input/index.ts
  src/components/Input/index.tsx
  src/components/Input/style.ts
  src/containers/NormalSignInModal/index.tsx
  src/containers/NormalSignupModal/index.tsx
  styles/theme.ts
Labels: fix

#58 Create meeting info Component
  public/imgs/RotatedImg.png
  src/components/MeetingInfo/MeetingInfo.style.tsx
  src/components/MeetingInfo/MeetingInfo.tsx
  src/components/MeetingInfo/index.stories.tsx
  src/components/MeetingInfo/index.ts
Labels: enhancement, feature

#55 Create ReviewList Component
  components/post/ReviewList/ReviewList.style.tsx
  components/post/ReviewList/ReviewList.tsx
  components/post/ReviewList/index.stories.tsx
  components/post/ReviewList/index.ts
Labels: enhancement, feature

#62 refactor: Refactor meeting-info src/components to components/post
  components/post/MeetingInfo/MeetingInfo.style.tsx
  components/post/MeetingInfo/MeetingInfo.tsx
  components/post/MeetingInfo/index.stories.tsx
  components/post/MeetingInfo/index.ts
Labels: refactoring

#57 Add semantic tag props to wrapper component, default value div
  components/common/SearchMenu/SearchMenu.tsx
  components/common/Wrapper/Wrapper.stories.tsx
  components/common/Wrapper/Wrapper.styled.ts
  components/common/Wrapper/Wrapper.tsx
Labels: fix
